### ISSUE TITLE
Backstage - Source Image

### ISSUE THREAD

**Issue by shadow3x3x3** [No-57/orange-backstage-api#40]
- [x] Prodcut Image Table: `product_imgs`

    | Column| Type|
    |--------|--------|
    | product_id| Integer|
    | path| string| 

    @asdfg429 You can select product iamges via product_id from this table.

- [x]  Image Source
    Fetching source image URL into database in crawlers. It the URL is not exsits, using mock image instead.
    
    @Vince-Ku There are two points to note.
    1. Images from MOMO are webp type, could you decode this type in iOS side?
    2. The mock image URL is https://picsum.photos/200/300, a redirected URL path. I think it could be handled by iOS http client.

**Comment by Vince-Ku** [comment]
> Images from MOMO are wepb type, could you decode this type in iOS side?
> The mock image URL is https://picsum.photos/200/300, a redirected URL path. I think it could be handled by iOS http client.

both are feasible.
